const ROLE_SHOP = {
  SHOP: "SHOP",
  ADMIN: "ADMIN",
  WRITER: "WRITER",
  EDITOR: "EDITOR"
};

const PERMISSION = {
  DEFAULT: "0000",
  1: "1111",
  2: "2222"
};
const PERMISSIONS = [PERMISSION.DEFAULT, PERMISSION[1], PERMISSION[2]];

module.exports = {
  ROLE_SHOP,
  PERMISSION,
  PERMISSIONS
};
